version: 2.1

jobs:
  Build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  Test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 test.py

workflows:
  Learn 0:
    jobs:
      - Build:
          requires: []
      - Test:
          requires: [Build]